### ISSUE TITLE
Subtraction underflow crash calculating backwards lane count

### ISSUE THREAD

**Issue by dmfutcher** [a-b-street/osm2streets#102]
Hi, I ran into a crash when trying to load Edinburgh, Scotland into A/B Street:
`thread 'main' panicked at 'attempt to subtract with overflow', /home/david/.cargo/git/checkouts/osm2streets-fbbbdf753e406749/a55aef7/osm2streets/src/lanes/classic.rs:110:20`

Did some debugging and saw [here](https://github.com/a-b-street/osm2streets/blob/main/osm2streets/src/lanes/classic.rs#L110), `n = 2` and `num_driving_fwd=3`, which doesn't make much sense, but was causing a crash. 

I added a workaround to check for situations where that subtraction would underflow and default to 0 backward lanes, diff here: https://github.com/a-b-street/osm2streets/compare/main...dmfutcher:osm2streets:fix-lanes-calculation-crash. This works and I successfully loaded Edinburgh, but I'm not sure if that's the "correct" way to fix it. I'd be happy to hack on this and submit a PR if you could give me some guidance on the correct way to handle this situation (I found this software looking for something to hack on for Hacktoberfest).

You can repro using this GeoJSON: https://gist.github.com/dmfutcher/2b906f1b2b953a62ea1da8b361ab2fed

**Comment by dabreegster** [comment]
Your fix looks good, please do send a PR! But also, could you print the osm
id of the offending road? We should fix the data there too, something seems
very wrong

**Comment by dabreegster** [comment]
Edinburgh looks alright after this fix! It's a huge area and slow to import / use, of course. The missing ocean is https://github.com/a-b-street/abstreet/issues/32. If you hit more problems or get interested in working on anything, let me know -- thanks for trying stuff out and sending a fix!
