### ISSUE TITLE
Simpler osm2lanes editor

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#132]
Eventually https://a-b-street.github.io/osm2lanes/editor/ will be a way to more easily fix lane tagging visually. Right now it's focused on a single way and doesn't show a map at all.

After a morning of manually fixing mistagged lane count and bus lanes using street explorer, I realized we could do something much simpler that'd be very quick to build and would immediately help out people who already know OSM tagging.

1) Something like street-explorer, but that just lets you pan around OSM and import a new area. Only show the lane marking layer; no layer toggling
2) After rendering somewhere, click a road segment. We'd check OSM way IDs and zoom out to highlight all segments of that same way
3) Pop up a key/value string tag table and let people manually edit
4) Regenerate lane specs and re-render after updates
5) Press a button to download a `.osc` file to open in JOSM, or later submit the change directly

This just smooths out the workflow I'm already doing right now manually, and I think would be a big step forward for the low effort required. And of course when we call osm2streets in this case, run minimal transformations; we want to edit OSM and so want to see as close a picture as possible. And in fact, if you click a road segment with multiple way IDs, we can bail out, since we somehow made some transformation there.

**Comment by dabreegster** [comment]
https://github.com/a-b-street/osm2streets/tree/lane_editor
Something wicked (simple) this way comes...
https://user-images.githubusercontent.com/1664407/204092426-b4fe329a-759e-450f-b1c5-86053818756f.mp4

**Comment by Robinlovelace** [comment]
Wow, that video above looks awesome! I think I was testing the wrong tool but FYI this is what I found when trying to add a car storage lane to the northern end of Scott Hall Road:


Uploading 2022-11-26 14-24-00.mp4…

Issues: diff seems to have removed the road name and no way to change type of parking?

Source: https://www.openstreetmap.org/way/23162214#map=17/53.84446/-1.53754 and https://www.google.com/maps/@53.8452842,-1.5364045,3a,75y,36.1h,60.02t/data=!3m6!1e1!3m4!1s4LqhDwLfY5N9jDLEOlCs0g!2e0!7i13312!8i6656

**Comment by dabreegster** [comment]
This tool isn't deployed yet and the osm2lanes one doesn't work yet. Little
more patience :)

**Comment by BudgieInWA** [comment]
I'd push for getting the lane layer rendering in JOSM as an alternative solution. That way, all of the osm editing behaviours are already handled, and we are only responsible for the visualisation half. (Implementing custom editing widgets and interacting via our own geometry will be trickier, but is not needed for MVC and will be so much more useful when they are implemented.)

I have a stub JOSM plugin that I got building while I was in the country the other month, I'll put it up in a repo. All we need next is bindings for java #68 and to implement rendering of the output geom in the JOSM rendering pipeline, which is straightforward.

**Comment by dabreegster** [comment]
It'd be awesome to not reinvent all the wheels in JOSM. OK, I'll see if I can get Java bindings started this week. Since #133 is almost at the point of being usable end-to-end, I'll also nudge it over the finish line, for the lazy among us who still aren't comfortable with JOSM controls. :)

**Comment by dabreegster** [comment]
https://a-b-street.github.io/osm2streets/lane_editor.html is now up. Some tasks that could make a beginner-friendly issue:

- Click off a road to reset the view
- Indicate the forwards direction of the road, to help with tagging. Maybe an arrow drawn alongside it? (This'd be a chance to mess with the Rust-WASM-JS bridge bit)
- Use https://github.com/osmlab/osm-auth or similar and get ready for submitting changes directly to the API
