### ISSUE TITLE
Pimp up the graphviz .dot output

### ISSUE THREAD

**Issue by BudgieInWA** [a-b-street/osm2streets#21]
If we want to pursue .dot as a visualisation tool, we could get pretty snazzy with it. We could encode a lot of information in the visual representation. Rendering it to svg in a browser also allows it to be interactive, which opens up a lot of options.

- [ ] Setting node `pos` might result in accurately graph layouts.
- [ ] Setting edge "weight" equal to (trimmed) length might be a good hint for certain layout algos.
- [ ] Use node style to represent Intersection Type
- [ ] use line styles to show number of lanes, etc.
- eventually use arrow heads to represent yield type.
- [ ] spell out attributes in the hover text somehow?

**Comment by dabreegster** [comment]
Should we close given #162?
