### ISSUE TITLE
Handle pbf input too

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#225]
Today we support XML input: https://github.com/a-b-street/osm2streets/blob/main/streets_reader/src/osm_reader/reader.rs

I've been using the `osmpbf` crate in other projects, like https://github.com/dabreegster/od2net/blob/main/od2net/src/network/create_from_osm.rs. We should support this in osm2streets too -- pbf files are so much smaller than xml, and can be faster to parse.

**Comment by sqrtM** [comment]
hey Dustin!

Been having a little look at this over the weekend and have a (mostly..) working quick and dirty version of this up and running over on my fork.

Used [this pbf](https://download.geofabrik.de/north-america/us/us-virgin-islands.html) for testing and have gotten some nice results on the outputs so far.

![image](https://github.com/a-b-street/osm2streets/assets/79169638/fceeb30c-25cd-473c-b3e7-b0a3427e965d)
(geojson data visualized)

![image](https://github.com/a-b-street/osm2streets/assets/79169638/87f144e2-d31b-4928-9cab-48974c6a868a)
(the dot file is exremely large so I wasn't able to get it visualized, but it seems correct).

I'll continue testing and working on this when I get a moment to do so. Hopefully I'll have something nice and clean and fully functional before too terribly long. 

Thanks and have a great rest of your weekend :) If you need anything just let me know.

**Comment by dabreegster** [comment]
Wow, awesome to see this! Let me know if you have any questions or hit weird problems with the codebase.

> (the dot file is exremely large so I wasn't able to get it visualized, but it seems correct)

I wouldn't worry about testing this much; I've never looked at any beyond a super tiny test area

**Comment by dabreegster** [comment]
I can look into it in detail in a few days maybe, but it sounds suspiciously similar to a problem I hit in https://github.com/a-b-street/abstreet/pull/1014 ages ago. Something about passing a vector of bytes breaks.

I would vote for moving on with the PR and not worrying about parsing pbf from WASM. I don't know of a great use case for it anyway; Overpass [doesn't output as pbf](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Output_format_(out:)). The goal of handling pbf at all in osm2streets is for native use cases, I think. The A/B Street import pipeline could get much faster and require less disk to store pbf than xml. But the web importer for osm2streets will probably keep handling xml, unless there's a nice API somewhere that can extract a bbox or polygon and output as pbf.

**Comment by sqrtM** [comment]
Okay, great, good stuff. 
In that case, I'll remove all the JS/WASM side changes and keep this PR focused on native. We'll consider the WASM/StreetExplorer stuff as a seperate issue and keep this PR nice and thin.

Be back when the fork is ready 👍 thanks a ton. have a nice day.
