### ISSUE TITLE
Turn lane shows arrows where there should be none

### ISSUE THREAD

**Issue by robhubi** [a-b-street/osm2streets#229]
**Real situation:**
![grafik](https://github.com/a-b-street/osm2streets/assets/38103976/f8517ed6-d7ec-4661-983a-5e1810c2e218)

Tags of [way 959894302](https://www.openstreetmap.org/way/959894302) :
```
lanes	3
lanes:forward	2
lanes:backward	1
	
cycleway:left	lane
cycleway:left:lane	advisory
cycleway:right	no
	
sidewalk:both	separate
foot	use_sidepath
	
turn:lanes:forward	left|
	
vehicle:lanes:backward	yes|yes
bicycle:lanes:backward	yes|designated
	
highway	primary
lit	yes
maxspeed	50
name	Sankt-Peter-Hauptstraße
oneway	no
ref	B67a
smoothness	excellent
surface	asphalt
```
**A/B Street (V0.3.49):**
Turning lane not correct
 
![grafik](https://github.com/a-b-street/osm2streets/assets/38103976/d4e36985-4cb2-4491-a7e4-073bea55a6de)

**Comment by dabreegster** [comment]
https://a-b-street.github.io/osm2streets/#19.2/47.05454/15.4741691
osm2streets isn't attempting lane-level turn markings yet. But backing up, https://www.openstreetmap.org/way/959894302 has `lanes=3` but winds up with 4 driving lanes and the cycle lane. Possible bug, @ginnyTheCat? I'm seeing 5 total travel lanes in Muv

**Comment by ginnyTheCat** [comment]
This is due to muv only removing the `cycleway:` in cases it finds the `cycleway:lanes` tags described [here](https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/Radwege#Tagging_weiterer_f%C3%BCr_den_Radverkehr_relevanter_Stra%C3%9Feneigenschaften,_Spurf%C3%BChrungen_und_Infrastrukturen). Widening this to `bicycle:lanes` as well would be an easy change resulting in only 4 travel lanes, without a bicycle lane but `bicycle=designated` on the leftmost lane which fits the [description of the situation on the ground](https://www.openstreetmap.org/way/194755336).

**Comment by ginnyTheCat** [comment]
It would disappear from the osm2streets view and only show the two car lanes then, as we don't show something special for `motor_vehicle=yes` + `bicycle=designated`.  I'm not entirely sure how the situation on the ground looks as the satellite. Maybe @robhubi could describe it a bit more.

I'm also not sure not ` bicycle:lanes` removing the cycleway would/should interact with `cycleway:{left, right}:track`.

**Comment by robhubi** [comment]
Current situation on the ground: https://kartaview.org/details/8717529/11
Rights of use from left to right:
![DSC02835_cr](https://github.com/a-b-street/osm2streets/assets/38103976/870f140f-03ae-4c99-a0b1-b9f091e18bb6)

1: Sidewalk

2: Cycle lane with a soft segregation,
* No compulsory use for cyclists
* Cars may also drive, but not continuously

3: Lane
* Cycling permitted, but not all the way, because cycling on the right is mandatory

4: Turning lane
* Cycling permitted,

5: Lane
* Cycling permitted,

6: Sidewalk

6 in front: bus lane
* Only for buses in regular service, cycling is permitted here with an additional sign

**Comment by dabreegster** [comment]
Just noting that https://a-b-street.github.io/osm2streets//#19.2/47.05454/15.4741691 could be useful to experiment with changes to the tagging

**Comment by ginnyTheCat** [comment]
It's fixed now in the most recent version of muv.

![Screenshot of osm2streets with the bicycle lane now missing](https://github.com/a-b-street/osm2streets/assets/35173023/06f04a58-28cf-4649-bcd2-cc356f9bdedd)

**Comment by dabreegster** [comment]
Thank you for the upstream fix!
