### ISSUE TITLE
Try switching to Muv

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#232]
https://gitlab.com/LeLuxNet/Muv/ is a new library that's doing the "osm2lanes" job of transforming OSM tags to lane data much better than the code currently used here or in the older https://github.com/a-b-street/osm2lanes experiment. We should try cutting over to it.

It could likely help with a number of bugs: #231, #230, #229, #223, #222, #91, #89.

It's a bigger project to try this cutover, but still somewhat self-contained. If anyone's interested in trying, please do!

**Comment by tordans** [comment]
@dabreegster do know of a place to learn more about Muv that that link? It does not give a lot of context or details :).

**Comment by dabreegster** [comment]
@GinnyTheCat is the author

**Comment by ginnyTheCat** [comment]
Hi,
I built a small example integrating muv-osm into osm2streets [here](https://github.com/ginnyTheCat/osm2streets/tree/muv) with a live example being deployed on https://muv.lelux.net/osm2streets which helps a lot in checking how streets parsed compare to the osm2lanes variant. Another way to check the muv-osm output on a more technical level is running `cargo r --example lanes -F lanes` in the `muv-osm` directory, inputting the tags and getting a lane-by-lane output.

Looking at the issues above #230, #222 and #89 work in muv already. Both way directions as in #91 are supported on the muv side, but have no mapping to osm2streets yet.

I'm working on documenting muv more but [at the example](https://gitlab.com/LeLuxNet/Muv/-/blob/main/muv-osm/examples/lanes.rs?ref_type=heads) or the [muv-osm to osm2lanes](https://github.com/ginnyTheCat/osm2streets/blob/muv/osm2lanes/src/algorithm.rs) source code should help a bit. If there are any more questions I'm more than happy to answer them here or wherever you prefer.

**Comment by robhubi** [comment]
An excellent site for test cases: https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/Radwege#Radfahrstreifen_in_Mittellage_.2F_Fahrradschleuse_.2F_Fahrradweichen

**Comment by ginnyTheCat** [comment]
Thanks a lot @robhubi.

When testing the examples I realized that due to the roads having both the `bicycle:lanes` and `cycleway=lane` (a fallback for data consumers not understanding the `:lanes` suffix) tags, the road would end up with two bike lanes instead of one. This behavior is now fixed, and the two examples with OSM links can be viewed in osm2streets (you might need to reload without cache for the new version to be loaded).

https://muv.lelux.net/osm2streets/#19.2/52.4776157/13.4265795
https://muv.lelux.net/osm2streets/#18.93/52.4685018/13.4418944

**Comment by dabreegster** [comment]
Hi @ginnyTheCat, one logistic question/request before we try integration: could you please set a license on the project?

**Comment by ginnyTheCat** [comment]
Of course. I was thinking of using the [MPL 2.0 license](https://www.mozilla.org/en-US/MPL/2.0/FAQ), which would allow osm2streets and A/B Street to fully use it. If that's ok on your side I would go ahead with that.

**Comment by dabreegster** [comment]
Yep, anything compatible with Apache 2 is fine by me!

**Comment by robhubi** [comment]
> When testing the examples I realized that due to the roads having both the `bicycle:lanes` and `cycleway=lane` (a fallback for data consumers not understanding the `:lanes` suffix) tags, the road would end up with two bike lanes instead of one.

I see the tags bicycle:lanes as a description of the access rights and cycleway=lane as a description of the structural design of the carriageway. The tags complement each other.

The examples look great.

**Comment by ginnyTheCat** [comment]
One recent addition to muv that could be interesting to osm2streets is the on road curb position. In case of a highway with `cycleway=lane`, `sidewalk=yes`, the kerb would be between the cycleway and the sidewalk. Change the cycleway into a `cycleway=track` and the curb now is between the cycleway and the roadway.

This information could be useful to align roads to `barrier=kerb` lines, as many ways without `placement` data are often misaligned to the center of the roadway, resulting in osm2streets overlapping the roadway with separately mapped sidewalks and cycleways next to the road. Aligning the kerbs would double up as a width estimate for roads with no `width` tagged.

**Comment by dabreegster** [comment]
That sounds fantastic; those overlap problems happen frequently. If you find any particular examples where this new approach would help, we should add them to the test cases in Street Explorer.

I'd like to pick this up, but with work right now, there's no way it's happening in the next few weeks. :\

**Comment by ginnyTheCat** [comment]
One example could be this road (https://a-b-street.github.io/osm2streets/#18.9/50.9283434/11.5841848 / https://muv.lelux.net/osm2streets/#19.2/50.928293/11.5843508) where a kerb is mapped but the road isn't fully centered and collides with the sidewalk, even enlarging the intersection.

![imagen](https://github.com/a-b-street/osm2streets/assets/35173023/51694df8-f04d-46c0-a9af-035cf28aa8bf)
![imagen](https://github.com/a-b-street/osm2streets/assets/35173023/4083524c-4dc7-4bfb-9d08-e61926ee9287)

**Comment by ginnyTheCat** [comment]
#231 is now supported on the muv side with `priority` implying `lanes=1`

https://muv.lelux.net/osm2streets/#18.97/48.60629/7.75187

**Comment by robhubi** [comment]
In general, the higher-ranking mode of transport is favoured. This would be option 3 with a parking lane and a kerb at the very edge.

**Comment by ginnyTheCat** [comment]
>In general, the higher-ranking mode of transport is favoured.

I don't really understand this part of the sentence, maybe you could explain that a bit more. The second part is makes sense.

**Comment by robhubi** [comment]
Imagine a road. No sidewalk. Pedestrians, cyclists and cars are on the road. What type of road is it: footpath, cycle path or street? In the case of shared use, the higher-ranking means of transport determines the type.

**Comment by ginnyTheCat** [comment]
Ah, yea ofc. That's how it's implemented in the demo right now and how I'm porting it to the demo as well. `osm2lanes`'s `LaneType` has a `SharedUse` type for shared bike/pedestrian ways. Maybe I'm gonna map that very specific type of shared use to that type.
I just got confused as I thought you were referring to the half-on-sidewalk parking mentioned above.

**Comment by dabreegster** [comment]
> the handling of curbs in half-on-sidewalk parking situations

I'm still confused what this means -- any real-world examples? Is this a sidewalk where cars are allowed to park on half of it, and there's a curb marking the boundary? I'm not sure I've seen these before, so just trying to understand

**Comment by ginnyTheCat** [comment]
The cars basically have two wheels on the sidewalk and two wheels on the road surface.

![picture of cars parking](https://upload.wikimedia.org/wikipedia/commons/e/ee/Gdansk_Aldony.jpg)
Here on the left the cars are parking on the sidewalk, while on the right they are parking half on the sidewalk, half on the street.

![photo of German parking sign](https://upload.wikimedia.org/wikipedia/commons/4/4b/Zeichen_315-55_-_Parken_halb_auf_Gehwegen_in_Fahrtrichtung_rechts%2C_StVO_1992.svg)
This the sign used in Germany for such situations for example.

They're not super common which is why handling them just as fancy versions of on-sidewalk parking when converting them to osm2lanes makes sense.
