### ISSUE TITLE
Broken intersection geometry

### ISSUE THREAD

**Issue by pswsm** [a-b-street/osm2streets#259]
I was checking some not too complicated intersections and found one the pretty much breaks the rendering. The more I zoomed out the bigger it got from one side.

Said intersection is at `41.37331/2.11642`.

May be related to #136 
![image](https://github.com/a-b-street/osm2streets/assets/53122461/eb1d6296-4a8b-4818-8083-f80486d4c03b)
![image](https://github.com/a-b-street/osm2streets/assets/53122461/8a1a1d99-5a56-4af6-8ff6-e04eb569f61f)

**Comment by dabreegster** [comment]
https://a-b-street.github.io/osm2streets/#16.93/41.373805/2.117175 as a handy link. It's looking like https://www.openstreetmap.org/way/82558926 and similar all get treated as "very short" roads and merged into the intersection. Not sure why, will dig in when I have some time. Thanks for reporting!

**Comment by dabreegster** [comment]
https://wiki.openstreetmap.org/wiki/Proposal:Junction%3Dintersection

**Comment by pswsm** [comment]
Alright I didn’t see that. I’ll remove that tag ASAP since it’s not a junction.

Thanks!

**Comment by pswsm** [comment]
Fixed tags and works fine, closing it
