### ISSUE TITLE
Wrong driving side for non-sovreign LHT jurisdictions inside RHT countries

### ISSUE THREAD

**Issue by Kovoschiz** [a-b-street/osm2streets#267]
Bidirectional roadways don't change to the correct side in Hong Kong, Macau, and US Virign Islands. They are `admin_level=3` "states", causing the geocoder to not recognize them as "country", and this difference skipped. 
This results in wrong lane layout (asymmetric lane count roads, and becomes inconsistent with divided roads), road marking orientation, and "movement arrows". I haven't noticed what happens with sidewalks. 
UK RHT overseas territories don't have this problem, being `admin_level=2` https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic#Worldwide_distribution_by_country

**Comment by Kovoschiz** [comment]
Ok I had not understood where the geocoder went. Now I see it's in https://github.com/a-b-street/country-geocoder ? But do you want to change that, as it's technically returning the correct sovereign states, only not for traffic jurisdiction.

**Comment by dabreegster** [comment]
You're right, country-geocoder is the place where this is happening. If you can suggest a fix or point to a different data source there, happy to make it. The geocoding could be used for more things in the future -- default speed limits, lane widths, lane marking styling -- but for now it just matters for the LHT/RHT. I'm fine with making changes to fix this there.

Alternatively, we could try switching to https://github.com/westnordost/country-boundaries-rust, based on data used in  StreetComplete and probably much more correct
