### ISSUE TITLE
Bring back driving side switch for special purposes

### ISSUE THREAD

**Issue by Kovoschiz** [a-b-street/osm2streets#268]
Override doubles as workaround of previous #267  
> Sometimes people want to explain a layout using LHT examples in RHT settings to RHT countries or the majority of the rest of world

Therefore it can be useful to the public. A personal example, Taiwan is a road safety hell (several magnitude worse than USA, akin to an undeveloped country), and they love to cite Japan or Commonwealth examples by mirroring aerial imagery.

**Comment by dabreegster** [comment]
Done, you can change it at the bottom of the "Processing Options" on the left. The results are weird when there are one-ways, since those will still point the original direction:
![image](https://github.com/a-b-street/osm2streets/assets/1664407/b8cec49d-cccb-498b-b86e-1bb3c42da7ef)
