### ISSUE TITLE
Consider a cargo workspace

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#27]
We now have a `Cargo.lock` for the library itself, for the tests, and for the web test browser. [Workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) would let us share build artifacts and reduce maintenance burden of updating dependencies in 3 places

**Comment by BudgieInWA** [comment]
Yes! I had seen that, but am not familiar with exactly how it all fits together: packages, crates, mods.

At the moment, the crate `streets` is at the root, and the other crates just happen to be located in the same directory, but otherwise have no relation?
