### ISSUE TITLE
Split out geometry implementation

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#3]
> [After discussing a bit about the idea of osm2streets itself (here we are!), **it talks about `geom` libraries**, starting at the bottom of this comment. -- ed]

## [Before osm2streets existed, looking at `InitialMap` and `RawMap`]

I think it's time to split out the [intersection geometry](https://a-b-street.github.io/docs/tech/map/geometry/index.html) algorithm into its own repository. The reasoning is similar to https://github.com/a-b-street/osm2lanes:

- it has a small, well-defined interface, and it's a hard problem
- it could definitely have wider applications out of A/B Street -- a first concrete one is in 3D Street now
- separating it from the rest of the code-base encourages other people to work on it
- it's an opportunity to rethink different parts of it

## The API / code to extract

https://github.com/a-b-street/abstreet/blob/master/map_model/src/make/initial/geometry.rs
Pretty well-contained in one file, but there's some complexity with extracting it. The API is roughly "take a list of road segment line-strings and widths all connected to one intersection. Produce a polygon for the intersection, and also trim the line-strings back from the intersection."

We need a _bit_ more, like a hint of if we should attempt a different algorithm that's more suitable for highway on/off ramps. That's based currently on OSM tags, but I  don't think this library should know about those. (In fact, the name is maybe not great -- the library has nothing to do with OSM technically.)

The big complication is how to handle intersections that A/B Street consolidates into one. There's a two-phase thing where we pre-trim the roads based on individual intersections, then merge the intersections and create one final polygon. I'm not exactly sure what that'll look like in the cleaned-up API.

## Testing

Right now, this code has no direct tests. There are screenshot diff tests set up for a few maps, but they're a very blunt instrument. `osm2lanes` is going so well because it's so natural to unit test -- clear input and output. I want to finally set up the same thing for this problem. The input is the line-strings and widths, the output is trimmed line-strings and a polygon. The difference is that a human can't look at a text representation of either one usefully. I think instead, the I/O can be GeoJSON files. We'll still do goldenfile testing, but at the much more granular level of a single intersection.

To actually do this, we need an easy workflow for running the tests, finding changed polygons, and doing a visual diff. Is there a small cross-platform GeoJSON viewer? I use QGIS or geojson.io normally, but both aren't quick to just launch from the command-line. I'm tempted to take some form of the RawMap editor UI as a tool for this project. That UI also lets people draw/edit roads and immediately update the intersection polygon. Alternatively, this could be an opportunity to try out some other simple UI framework.

## Splitting repository logistics

I cheated with `osm2lanes` and just copied A/B Street code into a new repo. A/B Street today doesn't depend on that repo at all, though I want to eventually cut over to it. But for osm2polygons, I want to start this properly -- immediately cut over A/B Street to depend on this new crate. This has a development convenience cost -- if there's a change to the algorithm that's best evaluated in A/B Street, we'd have to temporarily change `Cargo.toml` to point to a local copy. But that's the idea behind making the new repo very self-contained and well-tested on its own.

The harder question is dependencies! Luckily, the intersection geometry code doesn't depend on `abstutil` or `abstio`, so I don't have to figure out what to do with those monstrosities. :)  The question is `geom`, which is A/B Street's very sketchy geometry library. I started this thing at the very beginning because parts of `geo` didn't exist or I didn't understand them at the time. `geom` has all sorts of problems and basically 0 tests.

Option 1: split `geom` into its own repo, make both abstreet and the new osm2polygons depend on it.

Option 2: take this opportunity to make osm2polygons instead directly use `geo`. I haven't looked carefully through the code yet, but I think there aren't too many dependencies on tricky `geom` stuff. The main thing is operations on `PolyLines` (aka `geo::LineString`s) that slice it -- take a distance interval and return a new linestring. There's also linestring shifting -- projecting perpendicularly to the left/right...

Option 2A: Port the math in `geom` to work on `geo::LineString`s. If some of it isn't half-bad, could even contribute directly to georust, or make a new crate.

Option 2B: Look for replacements for some of these core operations. I know about https://github.com/jbuckmccready/cavalier_contours and maybe a few others. They're probably way more robust than wacky A/B Street stuff.

@michaelkirk, any opinions on any of this?

**Comment by BudgieInWA** [comment]
I have tweaked the title of this issue, because we have started towards the extraction (in all its complexities) and testing elsewhere, while there are valuable ideas about the `geom` libraries, that I think we should keep working on here.

**Comment by dabreegster** [comment]
> That said, I expect there'd be dividends in eventually making the types in geom a "New Type" wrapper for geo, that way all the geo algorithms are "at hand" and you don't need to worry about round tripping everything all the time, but you can still add your own trait impls.

I'm leaning more towards this now. If I had to categorize the parts of `geom` currently:

- could just wrap a `geo` object:  `Bounds` and `GPSBounds` (probably `Rect`), `LonLat` and `Pt2D`, `Line`, `Polygon`, `PolyLine`, `Ring`
- other geometric with no equivalent: `Angle`, `Circle`, `Distance`
- unrelated to geometry: `Duration`, `Percent`, `Speed`, `Statistic`, `Time`

I'm still not sure what the end-game looks like, but it could be very incremental work to go through that first list, make each type wrap a `geo` equivalent, and rethink the current API exposed. For example, abst `Polygon` immediately does ear-cutting to triangulate and stores the result. That was a very legacy decision I'd love to revisit.
