### ISSUE TITLE
Store the Test Browser state in the URL

### ISSUE THREAD

**Issue by BudgieInWA** [a-b-street/osm2streets#31]
The source of truth for a lot of the state of the web-app should be in the URL. This has a few benefits:

- your place is not lost if you reload,
- you can share "deep links" to specific data and setups,
- we can programatically generate links to specific app states,
- the OSM Smart Menu can be used to link to/from the tool.

The [`history.pushState` and `.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History) allow us to do this without reloading.

Specifics I can think of now:
- the currently loaded test case in the path
- the current layer configuration (when we have controls for hiding layers, etc.) in the query
- the current map position and zoom in the hash (like osm.org)

**Comment by dabreegster** [comment]
I need to do some reading about how non-framework JS places structure this sort of thing. When somebody changes a setting or clicks a link, I can think of a few ways to implement things.

1) Update the URL first. Then continue to mutably change the state of the app, calling methods to load a different test, reimport, etc.

2) Mutably change the app state. In all places that do some kind of state change, once it's done, then update the URL at the end.

3) Just update the URL, and call some big "router" function that checks the current state and the instructions and the URL and reconciles. This sounds kind of lofty and virtual DOM-like, but it's pretty simple for us... check if test name matches.

Things like the current map zoom/position get a bit weird. If you click a new test case, we need to override that position in the URL as we warp to the new place.

**Comment by dabreegster** [comment]
Mentioned in the call today -- change state without reloading the whole page
