### ISSUE TITLE
Cleanup street_network and import_streets crates

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#43]
These 2 crates were just moved over from the A/B Street repo. Now that the big transition is done, some smaller cleanup tasks.

- [x] Reorganize `street_networks/src/lib.rs` into more modules
- [x] Consistently call an instance of `StreetNetwork` something -- probably `streets`. Not `raw` or `map`.
- [x] Stop re-exporting all the types from `raw_map`; clean up callers to import from `street_network` (over on the abstreet side)
- [x] Clean up the weird dependency on `kml::ExtraShapes` for debugging. We should just output GeoJSON instead; don't need the weird wrappers. I'll probably rethink `ExtraShapes` in general; I made it up early before I knew how to sanely parse geojson in rust.
- [x] Update the `README` in this repo to explain the structure of the crates, and how we'll build multiple wrappers on top of `StreetNetwork`
- [ ] Add error handling to `import_streets`
- [ ] Reconsider `import_streets::Options`. There's a bunch of A/B Street-isms in there ignored by this repo.
- [ ] Slim down the public interface of `import_streets`. It should mostly just be `osm_to_street_network`, and over in abstreet, `convert_osm` should call that.

**Comment by dabreegster** [comment]
and @BudgieInWA, now that the 2 crates live over here, please scrutinize them more as you build on top of them. For example, the next big change I want to finish is cutting over to osm2lanes. That'll be a good example of how development in this repo proceeds, because my validation for that cutover will be to make sure there are no unintended consequences downstream in abstreet

**Comment by BudgieInWA** [comment]
> and @BudgieInWA, now that the 2 crates live over here, please scrutinize them more as you build on top of them. 

Great! I'm looking forward to making more changes directly in `street_network` rather than on top of it. The next deep dive I do on this project will be familiarising myself with the details of these new crates -- maybe implementing a "Slice" kind of intersection.

This split (and the cleanups that you will continue to do) should make it much easier for me to do so!

**Comment by dabreegster** [comment]
With #137 and other recent work, we can call this done, or there are more specific issues/ideas now that take precdence
