### ISSUE TITLE
Express transformations to run better

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#48]
https://github.com/a-b-street/osm2streets/blob/33081457c07223e364e60215373c1ea760408e1f/street_network/src/transform/mod.rs#L14

After initially turning `.osm.xml` into a `StreetNetwork`, the next step is usually to do `run_all_simplifications`. Right now this runs through a fixed sequence, taking a few boolean options. I've recently added a new user of osm2streets at https://github.com/dabreegster/bus_spotting, and requirements there are simpler -- I'd love to skip some expensive steps for collapsing degenerate intersections (ahem -- I mean `IntersectionComplexity::Connection`).

The simplest refactor would introduce a struct with options for each transformation, along with reasonable defaults. But potentially in the `map_editor` UI or the new StreetExplorer web app, it'd be useful to specify even more detail -- like running a single transformation step at a time, to step-through debug stuff. Maybe an `enum` of transformation steps (with some of them maybe taking more configurable parameters) would be more flexible, and then we take a sequence of these to execute.

**Comment by BudgieInWA** [comment]
Sounds good. Speciality transformations too, for speciality uses like routing a racing line or something.

It will be useful to run a list of transformations as part of creating a new `StreetNetwork` to get it into a valid state. (That way we can get the benefits of stepwise debugging and a clear way of expressing the order of steps.) Classifying intersections feels like part of `new`, but isolating it in its own transformation is nice.

**Comment by dabreegster** [comment]
I started this -- apologies for not waiting on a PR, I keep stomping on myself with all the open branches, and I'm starting to feel time pressure from SotM. Feel free to review at your leisure. I can also help rebase your open PR against any changes.

**Comment by BudgieInWA** [comment]
> I started this -- apologies for not waiting on a PR, I keep stomping on myself with all the open branches, and I'm starting to feel time pressure from SotM. Feel free to review at your leisure. I can also help rebase your open PR against any changes.

No worries. It was a surprise to see the merge conflict updating from `main`, but the level of documentation within the commit messages and how they're tied back to the GH issues is more than enough. Let's adopt a "merge first, then ask for forgiveness" attitude for this repo, where it unblocks subsequent changes. (e.g. I am a fan of immediately merged PRs as a place for discussion after the fact, and simply commenting on commits on GH too.)

**Comment by dabreegster** [comment]
I'm happy enough to call this issue closed: https://github.com/a-b-street/osm2streets/blob/99d2b73fbb1ed02dc578fcdbe32e00cee00dc357/street_network/src/transform/mod.rs#L63

The web app exposes some settings to enable optional steps. We could go crazy with that interface and let people drag-and-drop all possible steps and make up their own list, but that feels overkill at this point
