### ISSUE TITLE
Discuss adding geometries to osm2lanes

### ISSUE THREAD

**Issue by tordans** [a-b-street/osm2streets#5]
(More of a question/discussion/know how share-issue.)

The output at https://a-b-street.github.io/osm2lanes/ does not include geometries. I assume that the idea is, that osm2lanes only handles tags, not geometries?

I wonder, what the ideal process to render the data on a map would be. And if this might require a secondary shared project lanes2map.

What are your thought on how to render the data on a map. 
I assume ab-street transform the lane-data into areas and paints those? 
Is there a feasible way to instead use the lane-width to calculate lat/lng values with an offset based on the center line (respecting a-b-street/osm2streets#6).
Both approaches require to handle curves properly (but I have no idea how ;-)).

**Comment by BudgieInWA** [comment]
This whole new repo is our attempt to answer this question, thanks for asking :) I'm looking forward to hearing more from everyone on the many questions that this raises!
