### ISSUE TITLE
How to download intersections data as geojson?

### ISSUE THREAD

**Issue by droidmaniac31** [a-b-street/osm2streets#57]
Hello, I have imported the json data and the area data with intersections are showing. I would like to export all that processed data as geojson or shp file. 
Please help me on that. Thank you and waiting for your reply

**Comment by dabreegster** [comment]
Definitely. Any of these options sound better?

- drag a `.osm` file that you clip yourself to the browser, do the conversion there
- use the browser app, but be able to drag over a `.geojson` file with a boundary, and make a very large query to Overpass
- draw the boundary polygon in the browser app directly
- compile a CLI tool (requiring you to install Rust) and run it on a `.geojson` polygon, totally out of the browser

We could add a geojson export to the A/B Street UI, where you've already successfully imported a large area (I'm assuming). But I'd prefer to move away from cramming more features in there, especially when we have this new split-out tool that's more focused.

Also curious about your use case for the exported shapes. Is a polygon per road and intersection OK? What kind of properties/metadata about the objects are you interested in?

**Comment by Robinlovelace** [comment]
My 10 cents: from a reproducible research perspective the CLI tool option sounds good. All of the others sound good too and not sure what is best but big :+1: to the CLI option.

**Comment by GopiJogu** [comment]
Thank you @dabreegster really needed this.
Can you please show me an example in detail, how I can implement a CLI tool. (I apologize for asking, as I'm new at programming)?  Although I tried dragging  an.osm file into the OpenStreetMap web tool, it didn't really help! 
how can I implement any of  your suggested methods to export the geometry Geojson for a very large queries.
If you can let me know in detail that would be great.
My main objective is to obtain those intersection geometries for very large boundary extents.
Thank you.

**Comment by dabreegster** [comment]
Sorry for not being clear, I was asking which option sounded easiest as an end user, so I could choose what to implement. I decided to shove this into A/B Street for now, since it already has a nice experience for importing large areas. I'll cut a release before Friday and post instructions here how to use the tool.

I'll leave this issue open, because I think handling larger imports in the osm2streets web tool would be good too.

**Comment by dabreegster** [comment]
@GopiJogu, the workaround is:

1) Download the new version, https://github.com/a-b-street/abstreet/releases/tag/v0.3.29
2) Import your area
3) In the main view, press **Ctrl+S** to enable dev mode (bottom right corner)
4) Press **Ctrl+D** to enter debug mode
5) Scroll down the panel and click **export geometry to geojson**
6) There won't be any confirmation popup. But there should be a file called `map_geometry.json` that appears in the folder with A/B Street

**Comment by GopiJogu** [comment]
Hello @dabreegster 
Thanks for releasing new version early.

I've tried with a new version, After I import the new area into OpenStreetMap map viewer,
When I click **Ctrl+S** or **CTRL+D**, it shows nothing.
I'm sorry for troubling you, but can you help me out with this issue.
Please see the loom recording for better understanding of my issue.
Thanks again.

https://www.loom.com/share/71c81f1a6c894598b346b204424132ec

**Comment by dabreegster** [comment]
Ah, you need to run `game.exe` instead. On the title screen you'll click "Traffic sim sandbox" and then the **Ctrl+S** part

**Comment by dabreegster** [comment]
And you don't need to import again, all of the tools see the same cities. In the "select a district" panel instead of "Import a new city", scroll all the way down and choose "zz"
![Uploading Screenshot from 2022-08-11 15-06-39.png…]()

**Comment by GopiJogu** [comment]
I got it right now.
Thanks @dabreegster  for clear explanation. :)

**Comment by GopiJogu** [comment]
![Failure](https://user-images.githubusercontent.com/110944253/185573984-2a85c567-d25b-4206-b38b-a31bd4389aa5.jpg)

Hello, 
I am trying to import few areas, but I see this error (Please see attached screenshot)
Can you please help me on this one?

Thanks.

**Comment by dabreegster** [comment]
Send the geojson area please so I can reproduce this issue

**Comment by GopiJogu** [comment]
Hello, Please see the below area:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "MINX": 150.58804213000008,
        "MINY": -33.88317376899994,
        "MAXX": 150.82349939000005,
        "MAXY": -33.61228139899998,
        "CNTX": 150.70577076000006,
        "CNTY": -33.74772758399996,
        "AREA": 0.0637835751950892,
        "PERIM": 1.012699259999863,
        "HEIGHT": 0.2708923699999559,
        "WIDTH": 0.23545725999997558
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              150.82349939000005,
              -33.74430356376206
            ],
            [
              150.58804213000008,
              -33.74380365450516
            ],
            [
              150.58804213000008,
              -33.61228139899998
            ],
            [
              150.82349939000005,
              -33.61228139899998
            ],
            [
              150.82349939000005,
              -33.74430356376206
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by GopiJogu** [comment]
Hi @dabreegster 
Is there any update on this please?
Thank you.

**Comment by GopiJogu** [comment]
Hi
Sure. I understand.
Thank you. :)

**Comment by dabreegster** [comment]
@GopiJogu, https://github.com/a-b-street/abstreet/releases/tag/v0.3.32 should fix this. By the way, the area you sent generally doesn't have lanes tagged, so even big motorways show up as one lane by default. Depending what you want to do there, contributing some tagging to OSM would be useful!

**Comment by GopiJogu** [comment]
Thank you @dabreegster it would be very useful for me.
Is it possible for me to modify the width of every road at once?
If I can provide a custom width based on the classification of the highway?

**Comment by dabreegster** [comment]
@GopiJogu, this is controlled by https://github.com/a-b-street/osm2streets/blob/3fd448555a9153cfb417fe92df68d741e76055a6/street_network/src/types.rs#L354 right now. It's based on each lane, not the entire road. Ultimately I'd imagine to guess a reasonable default lane width would depend on the locale (suburban US vs middle of London) and OSM highway classification.

Sometimes you might know the entire road width from another source. If you can detangle exactly what that width captures (between the curb? Sidewalks and grass verges/), another needed algorithm would pick reasonable width values for all of the lanes so that the sum matches this value.

What exactly do you want to modify? And how willing are you to jump into the code?

**Comment by dabreegster** [comment]
No actionable followup here. We're still working towards locale-dependent lane width defaults.
