### ISSUE TITLE
Change default layer order to highlight geometries generated by osm2lanes

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/osm2streets#76]
As illustrated in the GIF below.

Should they be unticked to start with? I guess not, the road polygons are IMO one of the most useful features.
![Peek 2022-08-18 06-58](https://user-images.githubusercontent.com/1825120/185305219-92b8fb4a-5d0c-4063-9089-7767b7716873.gif)

**Comment by Robinlovelace** [comment]
OK it's more an issue with layer order. Will update the issue title accordingly.

Suggested fix: put the more interesting least intrusive layers on top by default meaning:

- Lane markings
- Lane polygons
- Geometry
- Then, finally, OSM

That's a logical starting order for me, otherwise the interesting geometries generated by osm2streets is obscured by the OSM geomtries that are already well-know.

Before: 

![image](https://user-images.githubusercontent.com/1825120/185305387-3d417726-1a82-4b21-bae5-b25edcdfdcc2.png)

After:

![image](https://user-images.githubusercontent.com/1825120/185305478-bd92e5be-4513-4781-af5f-ae17ae979333.png)

**Comment by dabreegster** [comment]
I'm misunderstanding how Leaflet chooses layer z-ordering. If you untick the "Imported area" group, it turns everything off. If you tick it again, it turns everything on, but following the order shown in the panel, and then it's correct. (OSM is on the lowest level, lane markings are on top).

I'll read a bit how it decides and try to fix this. Thanks for pointing it out!
