### ISSUE TITLE
Cycleway snapping transformation

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#78]
This has been started, but there's a great many places it needs work. Just starting to write down next steps / problems here.

1) https://www.openstreetmap.org/way/668997030 and nearby is an example in Leeds
2) https://www.openstreetmap.org/node/5739261534 is a simple one in London. The cycleway just rejoins the main road on one end, so the current pattern matching doesn't pick it up.

**Comment by Robinlovelace** [comment]
Another one in Leeds: https://www.openstreetmap.org/way/998245300

Without snapping: 
![image](https://user-images.githubusercontent.com/1825120/200409576-5c8e409d-730d-4b81-9028-cd8324ac4896.png)

Better with cycleway snapping experiment:

![image](https://user-images.githubusercontent.com/1825120/200410173-f4c457b1-80a6-4000-a73f-b3836c84f0d6.png)
