### ISSUE TITLE
Start a test suite

### ISSUE THREAD

**Issue by BudgieInWA** [a-b-street/osm2streets#8]
We want to be able to do something like
1. download a `.osm` of a small area,
2. fill in one of the expected outputs somehow, and
3. get the test to run.

Having test cases in place will be useful even before any implementations show up.

I can imagine fancy tests having these attributes:
- bounds: real world examples
- `.osm` xml: the example input
- network graph: rawmap graph structure and properties
- rawmap geojson: for snapshot testing/goldenfile testing
- ground truth: orthographic imagery for context when comparing snapshots

Would love to be able to write code against a *network graph from `.osm`* test.

**Comment by BudgieInWA** [comment]
@dabreegster, with the addition of some docs explaining an approach for

1. running tests: from `cd` to `cargo test`,
2. comparing and updating the goldenfiles, and
3. adding a new test (doing the goldenfile update pattern I guess),

I am happy to call the test suite "started", close this issue, and hack whatever I need on top of the existing tests, as I need them.

**Comment by dabreegster** [comment]
A separate test per directory would be ideal, I didn't look into it yet. That crate looks like it could work nicely!

So my TODOs:
- rename cfg.json -> test.json and output.json -> raw_map.geojson
- docs
- split tests

**Comment by BudgieInWA** [comment]
The very promising `tests` crate hits the nail on the head, testing multiple projects under the same roof.
