### ISSUE TITLE
Lookup driving side automatically

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/osm2streets#80]
Not sure if this is an OSM data issue but, this ain't right:

![image](https://user-images.githubusercontent.com/1825120/185782479-a79441bb-61d1-4197-ba9a-c72f32f7bf1f.png)

**Comment by dabreegster** [comment]
You need to use Settings to change driving side to left. #73 is in progress to figure this out automatically

**Comment by Robinlovelace** [comment]
Also: I need to update OSM to say sidewalk=no

**Comment by dabreegster** [comment]
I've never gotten the Overpass query for country to work. What if we do something... more brute-force? Per https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic, only 54 countries use left-handed driving. "admin 0 countries" from http://geojson.xyz/ is only about 600KB. Once stripping out 140 right-handed countries, removing all the properties, and maybe further simplifying the geometry, I bet we can get this file pretty small and quick to load. Would it be so crazy to just do a point-in-polygon check?

**Comment by dabreegster** [comment]
This isn't a crazy idea at all. https://github.com/westnordost/countryboundaries#speed is doing it already, reporting fantastic performance. Maybe the equivalent for us is to build a quadtree once and serialize it too, if that helps

**Comment by dabreegster** [comment]
https://github.com/a-b-street/osm2lanes/issues/103 is related.

https://github.com/streetcomplete/countrymetadata/blob/master/data/isLeftHandTraffic.yml
https://crates.io/crates/reverse_geocoder

I'm thinking:
- a small standalone Rust crate to do the query
- a quick python script to filter that geojson file using the YAML list

**Comment by dabreegster** [comment]
We might also be able to get rid of the double dependency in osm2lanes of `celes` and `locale-codes`

**Comment by Robinlovelace** [comment]
That would be another co-benefit :tada: watching this one with interest

**Comment by Robinlovelace** [comment]
In terms of the actual issue, realise I wasn't clear in the original post. The issue is with the sidewalks being on the inside. Reproducible example: https://a-b-street.github.io/osm2streets/#19.5/53.81977/-1.54114

**Comment by Robinlovelace** [comment]
Another issue with that view, this important shared use footway is not imported by osm2streets it seems: https://www.openstreetmap.org/way/1087921367#map=18/53.81506/-1.53894

Important one because the only way to go North up Scott Hall Road from Buslingthorpe Lane without mixing with fast moving traffic. Worthy of a new issue? Will open one if so.

**Comment by dabreegster** [comment]
Ah hmm, both of those are bugs. I'd like to keep this issue for autodetection of driving side, so do please open new issues if you don't mind. Thanks!

**Comment by dabreegster** [comment]
We now have automatic driving side lookup plumbed through everywhere! And the original issue with sidewalks on the inside is fixed on the deployed site:
![Screenshot from 2022-11-08 10-19-59](https://user-images.githubusercontent.com/1664407/200539327-340ecb18-d915-47ac-92ba-745394106482.png)
I'm still pretty sure the original problem was leaving the default right-handed driving, so the inferred sidewalks were put on the incorrect side

**Comment by Robinlovelace** [comment]
Amazing work, thanks for making adjustments for 'do everything different' Brits!
