### ISSUE TITLE
support highway=footway highway=steps highway=path

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/osm2streets#81]
Footways detached from roads are needed for two cases

(1) important footway that offers a shortcut accessible solely for pedestrians, used also in areas that use sidewalk tag to mark sidewalks

(2) in some regions (for example Poland) sidewalk tag is generally not used, sidewalks are tagged by mapping a separate `highway=footway`. In some cases such separately tagged footway had `footway=sidewalk` tag and road gets `sidewalk=separate` (though not always!).

Showing such detached footways is likely needed for (1) in order to get high quality simulation and is likely tricky/clunky for (2), though still would be immediate improvement for areas with such tagging.

**Comment by dabreegster** [comment]
I'm tentatively going to call this issue done! `highway=footway` cases are now both in osm2streets.org and A/B Street. Separately mapped sidewalks and crossings (`highway=footway, footway=sidewalk|crossing`) are still an open problem, covered by #59 / #4. There's probably plenty of refinements with the imported footways (some may be missing, or the geometry is very weird, or the rendering of different types of footway could be improved) but I'm sure specific followup tasks will emerge.
